# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_uploadfile_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='file_pos',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
