# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 05:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='file_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
