# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-01-08 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0003_auto_20170108_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadfile',
            name='file_pos',
        ),
    ]
